# For more information, see https://github.com/ChrisPenner/haskell-stack-travis-ci
language: c
sudo: true

git:
  submodules: false  # whether to recursively clone submodules

matrix:
  fast_finish: true
  include:
    # disable due to a sudo issue on osx. The doc claims there's a passwordless env but still ask for sudo password
    - env: BUILD_NAME=OSX
      os: osx

    # - env: BUILD_NAME=LINUX-AMD64
    #   os: linux
    #   dist: bionic
    #   arch: amd64

    # disable due to it takes too long
    # - env: BUILD_NAME=LINUX-ARM64
    #   os: linux
    #   dist: bionic
    #   arch: arm64

before_script:
 - unset CC
 - id
 - sudo -n true

# Here starts the actual work to be performed for the package under test;
# any command which exits with a non-zero exit code causes the build to fail.
script:
 - |
   # Run tests
   ./ci/DevOps/local/test/cb.sh

after_success:
 - |
   # Build and ship binary
   #./.travis/attach-binary.sh

# EOF
