# For more information, see https://github.com/ChrisPenner/haskell-stack-travis-ci
language: c
sudo: true

dist: bionic

git:
  submodules: false  # whether to recursively clone submodules

#cache:
#  directories:
#    - $HOME/.ghc
#    - $HOME/.cabal
#    - $HOME/.stack
#    - .stack-work
#  timeout: 1000

#matrix:
#  fast_finish: true
#  include:
#    - env: CACHE_NAME=8.2.2 STACK_YAML=stack.ghc8.2.yaml
#      compiler: ": #stack 8.2.2"
#
#    - env: CACHE_NAME=osx-8.2.2 STACK_YAML=stack.ghc8.2.yaml
#      os: osx
#      osx_image: xcode7.3
#      compiler: ": #stack 8.2.2"
#
#    - env: CACHE_NAME=8.4.4 STACK_YAML=stack.ghc8.4.yaml
#      compiler: ": #stack 8.4.4"
#
#    - env: CACHE_NAME=8.6.5 STACK_YAML=stack.ghc8.6.yaml
#      compiler: ": #stack 8.6.5"
#
#    - env: CACHE_NAME=osx-8.6.5 STACK_YAML=stack.ghc8.6.yaml
#      os: osx
#      osx_image: xcode11
#      compiler: ": #stack 8.6.5"

before_script:
 - unset CC
 - sudo apt-get update
 - sudo apt-get -y upgrade
 - sudo apt-get -y install git curl

# Here starts the actual work to be performed for the package under test;
# any command which exits with a non-zero exit code causes the build to fail.
script:
 - |
   # Run tests
   ./ci/DevOps/local/test/cb.sh

after_success:
 - |
   # Build and ship binary
   #./.travis/attach-binary.sh

# EOF
