# For more information, see https://github.com/ChrisPenner/haskell-stack-travis-ci
language: c
# sudo: true -- this is deprecated

git:
  submodules: false  # whether to recursively clone submodules

os: linux
dist: bionic

jobs:
  fast_finish: true
  include:
    # disable because some of the travis-ci osx images would ask password for sudo
    # - env: BUILD_NAME=OSX
    #   os: osx
    #   osx_image: xcode11.4

    - env: BUILD_NAME=LINUX-AMD64
      os: linux
      dist: bionic
      arch: amd64

    # disable due to it takes too long. For a successful build, it may take over 20 hours!
    # - env: BUILD_NAME=LINUX-ARM64
    #   os: linux
    #   dist: bionic
    #   arch: arm64

before_script:
 - unset CC
 - sudo -n true || echo "sudo password needed, may fail"
 - sudo -v

# Here starts the actual work to be performed for the package under test;
# any command which exits with a non-zero exit code causes the build to fail.
script:
 - |
   # Run tests
   ./ci/DevOps/local/test/cb.sh

after_success:
 - |
   # Build and ship binary
   # cd.sh will deploy the built image locally and push it to the docker hub
   # Because it needs to login to docker hub, you should define the following
   # two env variables in the travis-ci.org setting page of this repository
   # project_m36_DOCKER_HUB_USERNAME
   # project_m36_DOCKER_HUB_PASSWORD
   ./ci/DevOps/local/test/cd.sh

# EOF
